services:

  db:
    image: postgres:16.3-bookworm
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ctr4ever
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ctr4ever
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${{POSTGRES_USER}} -d ${{POSTGRES_DB}}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
