# coding=utf-8

DATABASE_DRIVER = 'postgresql'
DATABASE_HOST = '127.0.0.1'
DATABASE_PORT = 5432
DATABASE_USER = 'ctr4ever'
DATABASE_PASSWORD = 'test'
DATABASE_NAME = 'ctr4ever'

SQLALCHEMY_DATABASE_URI = f'{DATABASE_DRIVER}://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}'
APP_SECRET_KEY = 'Pr!kyWFKYguc@9Y=01*F(bU:1hv:Ac'
